format = "┌─  $all"

[character]
success_symbol = "[└─○](bold green)"
error_symbol = "[└─○](bold red)"

[nix_shell]
impure_msg = "[impure shell](bold red)"
pure_msg = "[pure shell](bold green)"
format = 'via [☃️ $state( \($name\))](bold blue) '
